In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf
import numpy as np

In [2]:
a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0)
total = a + b
print(a)
print(b)
print(total)

Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("add:0", shape=(), dtype=float32)


In [3]:
sess = tf.Session()

In [4]:
print(sess.run(total))

7.0


In [5]:
print(sess.run(
    {'ab':(a,b), 'total':total}
))

{'ab': (3.0, 4.0), 'total': 7.0}


#### Now play with tf.random_uniform

In [6]:
vec = tf.random_uniform(shape=(3,), name="Random_Vector")
out1 = vec+1
out2 = vec+2
print (sess.run(
    vec))
print (sess.run(
    vec))
print (sess.run(
    (out1,out2)))

[0.34730065 0.72056544 0.29422045]
[0.4871521  0.09694338 0.69220436]
(array([1.5515604, 1.520095 , 1.963813 ], dtype=float32), array([2.5515604, 2.5200949, 2.9638128], dtype=float32))


#### Now Placeholders

In [7]:
x = tf.placeholder(tf.float32, name="x")
y = tf.placeholder(tf.float32, name="y")
z = x + y

In [8]:
print (sess.run(z, 
                feed_dict={x:3, y: 4.5}
               ))

print (sess.run(z, 
                feed_dict={x: [1, 3],
                           y: [2, 4]}
               ))

7.5
[3. 7.]


#### Datasets

In [9]:
my_data = [
    [0, 1,],
    [2, 3,],
    [4, 5,],
    [6, 7,],
]

In [10]:
slices = tf.data.Dataset.from_tensor_slices(my_data)

In [11]:
next_item = slices.make_one_shot_iterator().get_next()

In [12]:
while True:
    try:
        print(sess.run(next_item))
        print(' ')
    except tf.errors.OutOfRangeError:
        break

[0 1]
 
[2 3]
 
[4 5]
 
[6 7]
 


#### Creating Layers

In [13]:
xx = tf.placeholder(tf.float32, shape=[None, 3])
linear_model = tf.layers.Dense(units=1, name="DenseLayer")
yy = linear_model(xx)

xxx = tf.placeholder(tf.float32, shape=[None,3])
yyy = tf.layers.dense(xxx, units=1)

In [14]:
init = tf.global_variables_initializer()
sess.run(init)

In [15]:
print(sess.run(
    yy,
    {xx: [[1,2,3],
          [4,5,6]]}
))

[[2.8370235]
 [6.468895 ]]


In [16]:
print(sess.run(
    yyy,
    {xxx: [[1,2,3],
          [4,5,6]]}
))

[[0.05928445]
 [3.2336154 ]]


#### Training the Model

In [17]:
Vx = tf.constant([[1],  [2],  [3],  [4]], dtype=tf.float32, name="Vx")
Vy = tf.constant([[0], [-1], [-2], [-3]], dtype=tf.float32, name="Vy")

In [18]:
linear_model2 = tf.layers.Dense(units=1, name="Linear_Model_2")

y_pred = linear_model2(Vx)
loss = tf.losses.mean_squared_error(labels=Vy, predictions=y_pred)

optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
for i in range(10):
    _, loss_value = sess.run((train, loss))
    print(loss_value)

print(sess.run(y_pred))

0.33067825
0.28398305
0.2512562
0.22822356
0.21191958
0.2002864
0.19189602
0.18575773
0.181184
0.17769776
[[-0.6406708]
 [-1.2760572]
 [-1.9114437]
 [-2.5468302]]


#### Write the Graph

In [19]:
writer = tf.summary.FileWriter('.')
writer.add_graph(tf.get_default_graph())